# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "controller"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2210
  config.vm.synced_folder "../data", "/home/vagrant_data"
end
