---
- name: playbook
  hosts: all
  become: yes
  user: vagrant
  gather_facts: False
  max_fail_percentage: 0
  vars:
    app_path: /vagrant
    home: /home
  tasks:
    # 言語を日本語に変更
    # 現在のシステムロケールを確認
    - name: check system locale
      command: localectl status
      register: res_localectl # タスクの実行結果を'res_localectl'に代入
      check_mode: no
      changed_when: false
    
    # LANGファイルをインストール
    - name: install language-pack-ja
      apt:
        name: language-pack-ja
        state: latest
      when: "'LANG=ja_JP.utf8' not in res_localectl.stdout"

    - name: changed locale
      command: localectl set-locale LANG=ja_JP.utf8
      when: "'LANG=ja_JP.utf8' not in res_localectl.stdout"
      
    # TimeZoneを変更
    # 現在のTimezoneを確認
    - name: check timezone
      command: timedatectl status
      register: res_TMdatactl
      check_mode: no
      changed_when: false

    #- name: debug var res_TMdatactl
    #  debug: 
    #    msg: "{{ res_TMdatactl }}"

    # timezone=Asia/Tokyo以外は変更
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo
      when: "'Time zone: Asia/Tokyo (JST, +0900)' not in res_TMdatactl.stdout"
    
    # desktopがインストールされているか確認
    - name: apt (check mode)
      apt:
        name: ubuntu-desktop
        state: present
      check_mode: true
      register: res_desktop_installed

    - name: debug var res_desktop_installed
      debug: 
        msg: "{{ res_desktop_installed }}"

    #- name: assert httpd installed
    #  assert:
    #    that:
    #      - result_desktop_installed.changed is false

    
    # 必要なパッケージをインストール
    #- name: Install multi packages
    #  apt:
    #    name:
    #      - ubuntu-desktop
    #      - docker
    #    state: latest