# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-19.10"
  config.vm.box_version = "202003.31.0"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "D:/My_programing/python", "/home/vagrant/vagrant_data", create: true

  # Virtual boxの設定
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true # GUIを起動する
    vb.memory = "2048" # メモリは2GB

    vb.customize [
      "modifyvm", :id,
      "--vram", "256", # ビデオメモリの確保（フルスクリーンモードにするため）
      "--clipboard", "bidirectional", # クリップボード共有
      "--draganddrop", "bidirectional", # ドラッグアンドドロップ可能に
      "--cpus", "2", # CPUは2つ
      "--ioapic", "on" # I/O APICを有効化
    ]
  end

  # Ansibleを用いて環境構築を行う
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "./playbook.yml"
  end

  # docker をインストールし，環境構築を行う
  config.vm.provision "docker" do |docker|
    
end